# Generated by Django 5.2.4 on 2025-07-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_name_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
